In this Exercise we will see how to feed a data from tfds into an ImageDataGenerator

In [23]:
import tensorflow_datasets as tfds
import tensorflow as tf
import numpy as np

In [24]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)

We first create an array. ImageDataGenerator expects a numpy array as an input

In [25]:
train_x = []
train_y = []

We then Populate the array with our image data and label data

In [26]:
for sample in data:
  train_x.append(sample[0].numpy())
  # train_y.append(sample[1].numpy())
  train_y.append(tf.keras.utils.to_categorical(sample[1].numpy(), num_classes=2))

In [27]:
train_x[0]

array([[[ 53,  55,  45],
        [ 46,  47,  40],
        [ 39,  40,  36],
        ...,
        [ 24,  25,  24],
        [ 21,  23,  21],
        [ 19,  21,  20]],

       [[ 41,  40,  34],
        [ 49,  48,  42],
        [ 54,  53,  48],
        ...,
        [ 18,  20,  19],
        [ 16,  18,  16],
        [ 16,  18,  16]],

       [[ 33,  29,  28],
        [ 50,  47,  42],
        [ 62,  58,  53],
        ...,
        [ 17,  19,  17],
        [ 15,  16,  14],
        [ 14,  15,  13]],

       ...,

       [[160, 143, 125],
        [162, 147, 129],
        [142, 128, 109],
        ...,
        [144, 124, 106],
        [141, 121, 104],
        [161, 141, 122]],

       [[142, 125, 107],
        [155, 134, 115],
        [153, 132, 113],
        ...,
        [149, 129, 113],
        [156, 134, 115],
        [163, 142, 123]],

       [[120, 101,  85],
        [123, 103,  87],
        [119, 101,  84],
        ...,
        [158, 136, 118],
        [163, 139, 120],
        [170, 149, 129]]

In [28]:
train_y[0]

array([1., 0.], dtype=float32)

We will also need to wrap it nicely with an array so that the dimension becomes (n * x * y *3). This is what we expect to be fed into the ImageDataGenerator

In [29]:
train_x = np.asarray(train_x)
train_y = np.asarray(train_y)

In [30]:
train_x[0]

array([[[ 53,  55,  45],
        [ 46,  47,  40],
        [ 39,  40,  36],
        ...,
        [ 24,  25,  24],
        [ 21,  23,  21],
        [ 19,  21,  20]],

       [[ 41,  40,  34],
        [ 49,  48,  42],
        [ 54,  53,  48],
        ...,
        [ 18,  20,  19],
        [ 16,  18,  16],
        [ 16,  18,  16]],

       [[ 33,  29,  28],
        [ 50,  47,  42],
        [ 62,  58,  53],
        ...,
        [ 17,  19,  17],
        [ 15,  16,  14],
        [ 14,  15,  13]],

       ...,

       [[160, 143, 125],
        [162, 147, 129],
        [142, 128, 109],
        ...,
        [144, 124, 106],
        [141, 121, 104],
        [161, 141, 122]],

       [[142, 125, 107],
        [155, 134, 115],
        [153, 132, 113],
        ...,
        [149, 129, 113],
        [156, 134, 115],
        [163, 142, 123]],

       [[120, 101,  85],
        [123, 103,  87],
        [119, 101,  84],
        ...,
        [158, 136, 118],
        [163, 139, 120],
        [170, 149, 129]]

In [31]:
train_y[0]

array([1., 0.], dtype=float32)

We then define the ImageDataGenerator

In [32]:
train_generator = tf.keras.preprocessing.image.ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    horizontal_flip=True)

Only required if featurewise_center or featurewise_std_normalization or zca_whitening are set to True.

In [33]:
train_generator.fit(train_x)

Try the Image Data Generator

In [38]:
# Testing
EPOCHS = 1
BATCH_SIZE = 16
for e in range(EPOCHS):
    for batch_x, batch_y in train_generator.flow(train_x, train_y, batch_size=BATCH_SIZE):
        print(batch_x, batch_y)
        break
        # Manually needs to break loop

[[[[ 0.49963364  0.36328313  0.188492  ]
   [ 0.53853303  0.37872046  0.188492  ]
   [ 0.56446594  0.3941578   0.2185719 ]
   ...
   [ 0.35700253  0.25522175  0.12833221]
   [ 0.34403604  0.23978442  0.11329227]
   [ 0.35700253  0.23978442  0.11329227]]

  [[ 0.51260006  0.36328313  0.20353195]
   [ 0.53853303  0.37872046  0.20353195]
   [ 0.53853303  0.3941578   0.20353195]
   ...
   [ 0.42183483  0.33240846  0.20353195]
   [ 0.40886837  0.30153376  0.17345206]
   [ 0.40886837  0.30153376  0.17345206]]

  [[ 0.51260006  0.37872046  0.2185719 ]
   [ 0.5255666   0.37872046  0.2185719 ]
   [ 0.51260006  0.36328313  0.20353195]
   ...
   [ 0.48666716  0.3941578   0.26369175]
   [ 0.4737007   0.37872046  0.2486518 ]
   [ 0.4737007   0.37872046  0.23361185]]

  ...

  [[ 0.31810313  0.20890974  0.02305258]
   [ 0.30513665  0.20890974  0.00801263]
   [ 0.30513665  0.20890974  0.00801263]
   ...
   [ 0.46073422  0.3941578   0.2185719 ]
   [ 0.48666716  0.42503247  0.2486518 ]
   [ 0.48666716 

Try the ImageDataGenerator for all of the data

In [34]:
BATCH_SIZE = 16
train_data = train_generator.flow(train_x, train_y)

In [35]:
train_data[0]

(array([[[[ 0.82379526,  1.6291449 ,  2.5648038 ],
          [ 0.82379526,  1.6291449 ,  2.5648038 ],
          [ 0.82379526,  1.6291449 ,  2.5648038 ],
          ...,
          [ 2.5353687 ,  3.1574414 ,  3.1363218 ],
          [ 2.4964693 ,  3.1265666 ,  3.1363218 ],
          [ 2.4575698 ,  3.095692  ,  3.1363218 ]],
 
         [[ 0.8367618 ,  1.6291449 ,  2.5648038 ],
          [ 0.8367618 ,  1.6291449 ,  2.5648038 ],
          [ 0.82379526,  1.6291449 ,  2.5648038 ],
          ...,
          [ 2.4835029 ,  3.1265666 ,  3.1363218 ],
          [ 2.4446034 ,  3.0802548 ,  3.1363218 ],
          [ 2.3927374 ,  3.0339427 ,  3.1363218 ]],
 
         [[ 0.8367618 ,  1.6445823 ,  2.5648038 ],
          [ 0.8367618 ,  1.6445823 ,  2.5798438 ],
          [ 0.8367618 ,  1.6445823 ,  2.5648038 ],
          ...,
          [ 2.405704  ,  3.0339427 ,  3.1363218 ],
          [ 2.3538382 ,  2.9876306 ,  3.1363218 ],
          [ 2.2890058 ,  2.9258814 ,  3.1363218 ]],
 
         ...,
 
         [[ 

In [39]:
model=tf.keras.models.Sequential([
        # YOUR CODE HERE, end with a Neuron Dense, activated by sigmoid
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(300, 300, 3)),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Conv2D(256, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(512, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(2, activation='softmax')
        ])

In [40]:
model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.RMSprop(0.0001), metrics=['accuracy'])

In [41]:
model.fit(train_data, epochs=5)

Epoch 1/5
33/33 [==============================] - 10s 220ms/step - loss: 0.6673 - accuracy: 0.5920
Epoch 2/5
33/33 [==============================] - 6s 185ms/step - loss: 0.4447 - accuracy: 0.8053
Epoch 3/5
33/33 [==============================] - 7s 207ms/step - loss: 0.1940 - accuracy: 0.9289
Epoch 4/5
33/33 [==============================] - 7s 220ms/step - loss: 0.1356 - accuracy: 0.9533
Epoch 5/5
33/33 [==============================] - 6s 191ms/step - loss: 0.0871 - accuracy: 0.9718


Try without using one hot encoding method of tensorflow

In [42]:
data2 = tfds.load('horses_or_humans', split='train', as_supervised=True)
train2_x = []
train2_y = []

In [43]:
for sample in data2:
  train2_x.append(sample[0].numpy())
  train2_y.append(sample[1].numpy())

In [44]:
train2_x = np.asarray(train2_x)
train2_y = np.asarray(train2_y)

In [45]:
train2_generator = tf.keras.preprocessing.image.ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    horizontal_flip=True)

In [46]:
train2_generator.fit(train2_x)

In [47]:
train2_data = train2_generator.flow(train2_x, train2_y)

In [48]:
model2=tf.keras.models.Sequential([
        # YOUR CODE HERE, end with a Neuron Dense, activated by sigmoid
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(300, 300, 3)),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Conv2D(256, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
        tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
        tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
        tf.keras.layers.MaxPooling2D(2, 2),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(512, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(1, activation='sigmoid')
        ])

In [49]:
model2.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.RMSprop(0.0001), metrics=['accuracy'])

In [50]:
model2.fit(train2_data, epochs=5)

Epoch 1/5
33/33 [==============================] - 11s 198ms/step - loss: 0.6631 - accuracy: 0.5755
Epoch 2/5
33/33 [==============================] - 7s 204ms/step - loss: 0.4339 - accuracy: 0.8043
Epoch 3/5
33/33 [==============================] - 7s 193ms/step - loss: 0.3263 - accuracy: 0.8695
Epoch 4/5
33/33 [==============================] - 6s 196ms/step - loss: 0.2031 - accuracy: 0.9279
Epoch 5/5
33/33 [==============================] - 7s 202ms/step - loss: 0.1342 - accuracy: 0.9523
